import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="mt-10">
          <ul className="flex items-center justify-center space-x-5">
            <li className="underline text-2xl">
              <Link href="/">Home</Link>
            </li>
            <li className="underline text-2xl">
              <Link href="/users">Users</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
